### ISSUE TITLE
azure-functions:package goal does not create actual package (ZIP)

### ISSUE THREAD

**Issue by JV-TMCZ** [microsoft/azure-maven-plugins#1175]
Problem: There is no way to create (independent) deployment package (ZIP file) for azure functions. Typically usage for CI/CD pipelines.

### Plugin name and version
com.microsoft.azure:azure-functions-maven-plugin:1.9.0

### Plugin configuration in your `pom.xml`
irelevant

### Expected behavior
mvn package or mvn azure-functions:package (default phase of azure-functions:package is package, so it should/could be equivalent)
should create actual PACKAGE (zip file). Deployment package for azure functions service is in format of ZIP file. 

There should be a maven goal to create a package. It should be already existing "package" goal. But it really does not matter - it could be another separated goal (e.g. goal name: "zip") or parameter to trigger it creation. To make a separate goal (ZIP) would have a advantage to save same IO operation during "normal" builds... 

Deployment package is needed for proper CI/CD pipeline. Where build pipeline (CI) creates artifact (ZIP file) and release pipeline (CD) use such artifact and perform a deploy action to target azure environment (subscription, resource group, resource name, ... ). Deployment package (ZIP) needs to be independent on deploy process.

### Actual behavior
Package to be deployed is created in azure-functions:deploy goal. Which is doing the deploy process - it is too late. 

PS: I could not find this in docs... if it is somewhere please point me to it.

**Comment by ghLinks** [comment]
Also interested in this, and when I run the azure-functions:package directly I get npe 
`Caused by: java.lang.NullPointerException                                                                                                                                                                            at java.util.zip.ZipFile.<init> (ZipFile.java:207)                                                                                                                                                               at java.util.zip.ZipFile.<init> (ZipFile.java:149)                                                                                                                                                               at java.util.jar.JarFile.<init> (JarFile.java:166)                                                                                                                                                               at java.util.jar.JarFile.<init> (JarFile.java:130)                                                                                                                                                               at com.microsoft.azure.common.Utils.getArtifactCompileVersion (Utils.java:30) `

**Comment by Flanker32** [comment]
@JV-TMCZ Thanks a lot for your report and really sorry for the late reply. For now there is no zip like goal in functions-maven-plugin, `package` will prepare all the resources in staging folder (by default `$(project_base)/target/azure-functions/$(your_app_name)`), and you may package the staging folder as a workaround(That's what `deploy` do). Besides, you may also try the azure-functions-gradle-plugin, which provide `azureFunctionsPackageZip` goal which should meet your needs, you may get the sample project [here](https://github.com/Azure-Samples/azure-functions-samples-java).

@ghLinks Thanks for your report, `azure-functions:deploy` goal depends on the result artifact of maven package, it may meet this issue if you execute `azure-functions:package`, we will enhance the error handing in later release.

**Comment by EspenSchei** [comment]
@ghLinks : For future reference, your problem can be solved by downgrading azure-functions-maven-plugin to version 1.6.
I got the same error in version 1.9, which was added when I created a project with maven archetype.

**Comment by mcasperson** [comment]
I ran into this same issue and documented a solution at https://stackoverflow.com/questions/74695741/how-can-i-deploy-a-prepackaged-quarkus-azure-functions-app/74695742#74695742.
