### ISSUE TITLE
azure-functions-maven-plugin : package creates weird files in root folder and tries to download core function tools

### ISSUE THREAD

**Issue by sijucm** [microsoft/azure-maven-plugins#1340]
### Plugin name and version
azure-functions-maven-plugin  1.9.2
### Plugin configuration in your `pom.xml`
Not relevant
### Expected behavior
package creates the function.json, etc in the target folder and DOES NOT create obj/ and extensions.csproj in the root folder. Also, this does not try to download the function core tools (because it fails in my azure pipeline). Examples for this tries to copy the local.settings.json to the target folder and that is not cool. local.settings.json is where we keep our secrets, keep your hand off it.
### Actual behavior
Microsoft, the example of using the pom with azure-functions-maven-plugin creates weird obj/ and extensions.csproj files on my local machine when doing mvn package command.

And when executing in azure devops it fails because the func-core-tools cannot be downloaded. I wonder why Microsoft decided to combine the packaging function and the local:run and deploy functions into one plugin and demand I give the configuration to my resource-group, etc. I will deploy it myself with the AzureFunctionDeploy in Azure devops.

Why does Microsoft think that it is cool to create an extensions.csproj file in my Java project when running mvn package? Am I the first person who tries to deploy an Azure java function using Azure devops? Are the rest of them still playing with hello world deployments?

Microsoft, please let me do the packaging of the function and without all the nice run-local and deploy functionality. Or at least let me know how to package without the azure-functions-maven-plugin and what to include in the package and I can do it myself. 

### Steps to reproduce the problem
Just configure this plugin and run the mvn clean package when using a function with input bindings connecting to cosmosdb (or storage account).

**Comment by Flanker32** [comment]
@sijucm Thanks for your report and really sorry for the late reply. Since Azure Functions 2.x, the functions runtime only includes HTTP and timer triggers by default. Other triggers and bindings are available as separate packages. So we need to install required extensions with function core tools,  which may create the `/obj` and `extensions.cspcsproj`

To solve this issue, we recommand to use function bundles, you just need to set the bundle information in `host.json`, please refer [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register) for more information..

Besides, the independent package goal is in our backlog, I'll update here once there are updates for this feature. As a workaround, you may try the gradle plugin, which could package the project with goal `./gradlew azureFunctionsPackage`, you may get the sample project [here](https://github.com/Azure-Samples/azure-functions-samples-java).
