### ISSUE TITLE
azure-function-maven-plugin version 1.3.4 does not work anymore

### ISSUE THREAD

**Issue by mnriem** [Microsoft/azure-maven-plugins#1825]
### Plugin name and version
azure-function-maven-plugin version 1.3.4 

The 1.3.4 version of the plugin does not work anymore. 

The underlying auth fails.

Upgrading to the 1.14.1 version solves the problem.

**Comment by Flanker32** [comment]
@mnriem Thanks a lot for your report! Azure cli has made a breaking change since 2.30.0, deprecated old authentication and migrate to MSAL, which was not supported by old maven plugins, you may get more info from [here](https://docs.microsoft.com/en-us/cli/azure/msal-based-azure-cli). 

Azure maven tooling has migrated to azure identity library for authentication which support authentication with latest azure cli, please upgrade to the latest maven plugin when meet this issue.
