### ISSUE TITLE
Maintain pom.xml files in master/develop branches with -SNAPSHOT version

### ISSUE THREAD

**Issue by brunoborges** [Microsoft/azure-maven-plugins#190]
To allow contributors to easily enhance and build the Maven plugins locally, all pom.xml files here must be set for -SNAPSHOT versions.

Versions must be set for actual release version only during release phase, and properly tagged in the git repository. 

This avoids local development builds referencing already published versions, creating conflicts and uncertainty about which version is being used.

**Comment by jdneo** [comment]
How about the version in master is the actual version in Maven Central. develop is always with -SNAPSHOT.

For example:

master: 1.2.0
develop: 1.3.0-SNAPSHOT

**Comment by brunoborges** [comment]
How about master being always the 'trunk' (under development) version, and then for releases we use tags? 

master: 1.3.0-SNAPSHOT
tags: 
- v1.0.1
- v1.0.2
- v1.1.3
- v1.2.0

**Comment by jdneo** [comment]
I see. Do you mean we remove the current `develop` branch and make the `master` branch to act as the current `develop` branch. Am I right?

**Comment by brunoborges** [comment]
Correct. It simplifies a lot.

**Comment by jdneo** [comment]
I see, actually I'm also a fan of single-master branch model.

Seems that in order to switch to single-master branch model, we will also need to change the current CI process.

Currently, we have some integration tests in the CI configurations which contains some auth credential for Azure. Those ITs will do some real deployments. So we disable the ITs when it comes to a PR, since the credentials cannot be accessed by a forked repo.

Each time we merge the codes from dev -> master, those ITs will be run to act as a kind of pre-release tests.

By adopting the single-master branch model. Seems we need to setup a new CI to run the ITs but its status check is not required for each PR. 

Other solution comes up in my mind is that we still disable the ITs for each PR. But we do it for each push, so when we are going to release. We will checkout a branch named `release-*` from master. Then when we push this release branch to the origin repo, the ITs will be triggered.

@brunoborges What do you think? Do you have some other suggestions?

**Comment by brunoborges** [comment]
This issue is related to https://github.com/Azure/azure-functions-java-library/issues/16

**Comment by brunoborges** [comment]
Also impacts https://github.com/Azure/azure-functions-java-worker/issues/140.

**Comment by jdneo** [comment]
Close this issue since the codes in master/develop branch are all with -SNAPSHOT suffix now.

**Comment by Jorge2M** [comment]
Then in the release phase is needed an automatic commit to replace 1.3.0-SNAPSHOT in the master branch for 1.4.0-SNAPSHOT

I'm right?

**Comment by brunoborges** [comment]
Once a release is done, yeah.
