### ISSUE TITLE
azure-functions-maven-plugin: Unable to select which Azure subscription to use

### ISSUE THREAD

**Issue by jo3yk** [Microsoft/azure-maven-plugins#289]
### Plugin name and version

azure-functions-maven-plugin:1.0.0-beta-2

### Plugin configuration in your `pom.xml`

As generated.

### Expected behavior
There should be an option to select which Azure subscription to use, similar to publishing a C# function.

### Actual behavior
Function app is always deployed to the default subscription. This behaviour persists if:

- Subscriptions in azureProfile.json are reordered so that the desired one is first.
- Desired subscription ID is set in clouds.config
- Default directory is changed to the desired subscription in the Azure portal
- Default subscription is changed via Powershell

### Steps to reproduce the problem

1. Follow the tutorial at [https://docs.microsoft.com/en-gb/azure/azure-functions/functions-create-first-java-maven](https://docs.microsoft.com/en-gb/azure/azure-functions/functions-create-first-java-maven) to create a basic function.
2. Login to Azure with an account with multiple subscriptions.
3. Attempt to deploy to a non-default subscription.

**Comment by jdneo** [comment]
@jo3yk Thanks for the feedback. Could you please share the tool you are using to deploy C# function? That will help us to understand the better experience.

**Comment by jo3yk** [comment]
@jdneo On the C# side I'm simply using the Publish option in VS2017 - per the basic tutorial https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio

**Comment by jdneo** [comment]
@jo3yk 

I see. Currently, we are using Azure CLI as our default authentication method, which results that the the subsciption Id cannot be specified during deployment. But there might be several ways that can help you:

- Use other authentication method, for example: [Use the Maven settings.xml file](https://github.com/Microsoft/azure-maven-plugins/blob/develop/docs/common-configuration.md#authentication-method-1-use-the-maven-settingsxml-file) or [Use an authentication file](https://github.com/Microsoft/azure-maven-plugins/blob/develop/docs/common-configuration.md#authentication-method-2-use-an-authentication-file)

- Use VS Code extension to publish the your project, see: https://code.visualstudio.com/docs/java/java-serverless#_deploy-the-function-to-azure

Please let me know if this can help you.

**Comment by jo3yk** [comment]
@jdneo 
Thanks very much! I hadn't seen those docs - it would be helpful if they were linked from the main Azure Functions docs (https://docs.microsoft.com/en-us/azure/azure-functions/) 
I've been able to do it with the VS Code extension so that will do nicely. Thanks again for your help.

**Comment by D43m0n** [comment]
I don't understand why this issue is closed while the third authentication method is still not usable when you have multiple subscriptions at your disposal. Then either update [the documentation](https://github.com/Microsoft/azure-maven-plugins/blob/develop/docs/common-configuration.md#authentication-method-1-use-the-maven-settingsxml-file) to reflect to this behavior, or please add the possibility for maven to follow the current, active, default subscription you just set with `az account set --subscription <subscription Id>`.  Because the [quickstart](https://docs.microsoft.com/nl-nl/azure/app-service/containers/quickstart-java) makes no note of a situation with multiple subscriptions at your disposal 😁

**Comment by Flanker32** [comment]
@D43m0n Sorry for the delay, now we have added a new attribute `<subscriptionId>` to solve this issue, you could add this attribute to `<configuration>` to select which subscription you want to use.

**Comment by zhughes3** [comment]
@Flanker32 I am using mvn's `settings.xml` to add service principal configuration.

When I run `mvn azure-functions:deploy` passing in resource group and function app name, it will try to deploy it to another subscription which the function app isn't scoped to.

So I tried adding subscriptionId to the configuration object in settings.xml. This is what that looks like:

```
<server>
      <id>AUTH_ID</id>
      <configuration>
        <client>SP_CLIENT_ID</client>
        <tenant>TENANT_ID</tenant>
        <key>SECRET_KEY</key>
        <environment>AZURE</environment>
        <subscriptionId>SUBSCRIPTION_ID</subscriptionId>
      </configuration>
    </server>
```

Even when I add the explicit subscription id, Azure uses my other subscription, the default subscription. This just started breaking our CD pipeline this past week after months of working fine.

**Comment by Flanker32** [comment]
> @Flanker32 I am using mvn's `settings.xml` to add service principal configuration.
> 
> When I run `mvn azure-functions:deploy` passing in resource group and function app name, it will try to deploy it to another subscription which the function app isn't scoped to.
> 
> So I tried adding subscriptionId to the configuration object in settings.xml. This is what that looks like:
> 
> ```
> <server>
>       <id>AUTH_ID</id>
>       <configuration>
>         <client>SP_CLIENT_ID</client>
>         <tenant>TENANT_ID</tenant>
>         <key>SECRET_KEY</key>
>         <environment>AZURE</environment>
>         <subscriptionId>SUBSCRIPTION_ID</subscriptionId>
>       </configuration>
>     </server>
> ```
> 
> Even when I add the explicit subscription id, Azure uses my other subscription, the default subscription. This just started breaking our CD pipeline this past week after months of working fine.

@zhughes3 Sorry for reply late, please set the `<subscriptionId>` in function plugin configuration, for now we didn't support set subscription id in `setting.xml`
```
<plugin>
   <groupId>com.microsoft.azure</groupId>
   <artifactId>azure-functions-maven-plugin</artifactId>
   <configuration>
      <subscriptionId>your-subscription-guid</subscriptionId>
      ...
   </configuration>
</plugin>
```

**Comment by vnextcoder** [comment]
This Issue also happens if you are having AZ CLI installed within WSL 2 and running MVNW from WSL2 only.

For troubleshooting this on WSL , I tried all steps necessary to clear the Subscriptions, Set Default Subscription from Command Line and also set <subscriptionId></subscriptionId> in the pom.xml as well. 

thing is the Azure.Subscriptions.list() just returns nothing. it could be a bug within the Azure Management JAR itself, but I am not sure as of now. 

Moreover, I have also tried using Maven Azure Plugin 1.7, 1.9.1 and 1.10.0 as well. All failed on  WSL2

Once I switched to the Windows 10 native, it worked fine.
