### ISSUE TITLE
Functions Plugin: Make FUNCTIONS_WORKER_RUNTIME set for java by default

### ISSUE THREAD

**Issue by brunoborges** [microsoft/azure-maven-plugins#400]
### Plugin name and version
The property `FUNCTIONS_WORKER_RUNTIME` should not be required as explicitly set property, since this is a Maven plugin for Java functions.

### Plugin configuration in your `pom.xml`
```xml
            <plugin>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-functions-maven-plugin</artifactId>
                <configuration>
                    <resourceGroup>myResourceGroup</resourceGroup>
                    <appName>myfuncapp</appName>
                    <appSettings>
                        <property>
                            <name>FUNCTIONS_EXTENSION_VERSION</name>
                            <value>beta</value>
                        </property>
                        <property>
                            <name>FUNCTIONS_WORKER_RUNTIME</name>
                            <value>java</value>
                        </property>
                    </appSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>package-functions</id>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by jdneo** [comment]
@pragnagopa any thoughts?

**Comment by pragnagopa** [comment]
Makes sense. Can we set this as part of deployment?

**Comment by jdneo** [comment]
@brunoborges @pragnagopa 

Do you mean we need to add this setting implicitly during the deployment instead of setting it explicitly in the plugin configuration?

If our goal is to simplify the configuration, besides remove it in the archetype, I think one way we could do is to check the setting during deployment:
- If this setting is not set, adding it
- If this setting is set and is set to `java`, we are good
- If this setting is set but not `java`, we show a warning

Meanwhile, we need to output messages to make sure the deployment will be as transparent as possible

**Comment by Flanker32** [comment]
Done in #653

**Comment by Ferrarilambo1020** [comment]
> Ensure that the archetype does not have this property explicitly set in the template.
> 
> [microsoft/azure-maven-archetypes#71](https://github.com/microsoft/azure-maven-archetypes/issues/71)

axelfernandogarcia48@gmail.com

**Comment by Ferrarilambo1020** [comment]
1. 

> ### **__**
